// Copyright 2020 Cambricon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package collector

const (
	Cndev        = "cndev"
	PodResources = "podresources"
	Cnpapi       = "cnpapi"
	Host         = "host"

	ArmOsMemTotal                     = "arm_os_memory_total"
	ArmOsMemUsed                      = "arm_os_memory_used"
	Capacity                          = "capacity"
	ChipCPUUtil                       = "chip_cpu_utilization"
	CoreUtil                          = "core_utilization"
	D2DCRCError                       = "d2d_crc_error_total"
	D2DCRCErrorOverflow               = "d2d_crc_error_overflow_total"
	DDRDataWidth                      = "ddr_data_width"
	DDRBandWidth                      = "ddr_band_width"
	ECCAddressForbiddenError          = "ecc_address_forbidden_error_total"
	ECCCorrectedError                 = "ecc_corrected_error_total"
	ECCMultipleError                  = "ecc_multiple_error_total"
	ECCMultipleMultipleError          = "ecc_multiple_multiple_error_total"
	ECCMultipleOneError               = "ecc_multiple_one_error_total"
	ECCOneBitError                    = "ecc_one_bit_error_total"
	ECCTotalError                     = "ecc_error_total"
	ECCUncorrectedError               = "ecc_uncorrected_error_total"
	FanSpeed                          = "fan_speed"
	Health                            = "health"
	ImageCodecUtil                    = "image_codec_utilization"
	MemTotal                          = "memory_total"
	MemUsed                           = "memory_used"
	MemUtil                           = "memory_utilization"
	MLULinkCapabilityP2PTransfer      = "mlulink_p2p_transfer_capability"
	MLULinkCapabilityInterlakenSerdes = "mlulink_interlaken_serdes_capability"
	MLULinkCounterCntrReadByte        = "mlulink_cntr_read_byte_total"
	MLULinkCounterCntrReadPackage     = "mlulink_cntr_read_package_total"
	MLULinkCounterCntrWriteByte       = "mlulink_cntr_write_byte_total"
	MLULinkCounterCntrWritePackage    = "mlulink_cntr_write_package_total"
	MLULinkCounterErrCorrected        = "mlulink_err_corrected_total"
	MLULinkCounterErrCRC24            = "mlulink_err_crc24_total"
	MLULinkCounterErrCRC32            = "mlulink_err_crc32_total"
	MLULinkCounterErrEccDouble        = "mlulink_err_ecc_double_total"
	MLULinkCounterErrFatal            = "mlulink_err_fatal_total"
	MLULinkCounterErrReplay           = "mlulink_err_replay_total"
	MLULinkCounterErrUncorrected      = "mlulink_err_uncorrected_total"
	MLULinkPortMode                   = "mlulink_port_mode"
	MLULinkSpeedFormat                = "mlulink_speed_format"
	MLULinkSpeedValue                 = "mlulink_speed"
	MLULinkStatusIsActive             = "mlulink_status"
	MLULinkStatusSerdesState          = "mlulink_serdes_status"
	MLULinkVersion                    = "mlulink_version"
	NUMANodeID                        = "numa_node_id"
	PCIeInfo                          = "pcie_info"
	PowerUsage                        = "power_usage"
	ProcessIpuUtil                    = "process_ipu_utilization"
	ProcessJpuUtil                    = "process_jpu_utilization"
	ProcessMemoryUtil                 = "process_memory_utilization"
	ProcessVpuDecodeUtil              = "process_vpu_decode_utilization"
	ProcessVpuEncodeUtil              = "process_vpu_encode_utilization"
	Temperature                       = "temperature"
	TinyCoreUtil                      = "tiny_core_utilization"
	Usage                             = "usage"
	Util                              = "utilization"
	Version                           = "version"
	VideoCodecUtil                    = "video_codec_utilization"
	VirtualFunctionMemUtil            = "virtual_function_memory_utilization"
	VirtualFunctionUtil               = "virtual_function_utilization"
	VirtualMemTotal                   = "virtual_memory_total"
	VirtualMemUsed                    = "virtual_memory_used"

	Allocated = "allocated"
	Container = "container"

	PCIeRead     = "pcie_read"
	PCIeWrite    = "pcie_write"
	DramRead     = "dram_read"
	DramWrite    = "dram_write"
	MLULinkRead  = "mlulink_read"
	MLULinkWrite = "mlulink_write"

	HostCPUTotal = "host_cpu_total"
	HostCPUIdle  = "host_cpu_idle"
	HostMemTotal = "host_memory_total"
	HostMemFree  = "host_memory_free"

	MLU                 = "mlu"
	Model               = "model"
	Type                = "type"
	SN                  = "sn"
	UUID                = "uuid"
	Node                = "node"
	Cluster             = "cluster"
	Core                = "core"
	CPUCore             = "cpu_core"
	MCU                 = "mcu"
	Driver              = "driver"
	Link                = "link"
	LinkVersion         = "link_version"
	PCIeSlot            = "pcie_slot"
	PCIeSubsystem       = "pcie_subsystem"
	PCIeDeviceID        = "pcie_device_id"
	PCIeVendor          = "pcie_vendor"
	PCIeSubsystemVendor = "pcie_subsystem_vendor"
	PCIeID              = "pcie_id"
	PCIeSpeed           = "pcie_speed"
	PCIeWidth           = "pcie_width"
	Pid                 = "pid"

	Namespace = "namespace"
	Pod       = "pod"
	VF        = "vf"
)
