// Copyright 2020 Cambricon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package collector

const (
	Cndev        = "cndev"
	PodResources = "podresources"
	Host         = "host"

	ArmOsMemTotal                     = "arm_os_memory_total"
	ArmOsMemUsed                      = "arm_os_memory_used"
	ChipCPUUtil                       = "chip_cpu_utilization"
	ChipTemperature                   = "chip_temperature"
	ClusterTemperature                = "cluster_temperature"
	CoreUtil                          = "core_utilization"
	D2DCRCError                       = "d2d_crc_error_total"
	D2DCRCErrorOverflow               = "d2d_crc_error_overflow_total"
	DDRBandWidth                      = "ddr_band_width"
	DDRDataWidth                      = "ddr_data_width"
	DDRFrequency                      = "ddr_frequency"
	DoubleBitRetiredPageCount         = "double_bit_retired_page_count"
	DramEccDbeCount                   = "dram_ecc_dbe_count"
	DramEccSbeCount                   = "dram_ecc_sbe_count"
	ECCAddressForbiddenError          = "ecc_address_forbidden_error_total"
	ECCCorrectedError                 = "ecc_corrected_error_total"
	ECCMultipleError                  = "ecc_multiple_error_total"
	ECCMultipleMultipleError          = "ecc_multiple_multiple_error_total"
	ECCMultipleOneError               = "ecc_multiple_one_error_total"
	ECCOneBitError                    = "ecc_one_bit_error_total"
	ECCTotalError                     = "ecc_error_total"
	ECCUncorrectedError               = "ecc_uncorrected_error_total"
	FanSpeed                          = "fan_speed"
	Frequency                         = "frequency"
	Health                            = "health"
	HeartbeatCount                    = "heartbeat_count"
	ImageCodecUtil                    = "image_codec_utilization"
	MachineMLUNums                    = "machine_mlu_nums"
	MemTemperature                    = "memory_temperature"
	MemTotal                          = "memory_total"
	MemUsed                           = "memory_used"
	MemUtil                           = "memory_utilization"
	MLULinkCapabilityP2PTransfer      = "mlulink_p2p_transfer_capability"
	MLULinkCapabilityInterlakenSerdes = "mlulink_interlaken_serdes_capability"
	MLULinkCounterCntrCnpPackage      = "mlulink_cntr_cnp_package_total"
	MLULinkCounterCntrPfcPackage      = "mlulink_cntr_pfc_package_total"
	MLULinkCounterCntrReadByte        = "mlulink_cntr_read_byte_total"
	MLULinkCounterCntrReadPackage     = "mlulink_cntr_read_package_total"
	MLULinkCounterCntrWriteByte       = "mlulink_cntr_write_byte_total"
	MLULinkCounterCntrWritePackage    = "mlulink_cntr_write_package_total"
	MLULinkCounterErrCorrected        = "mlulink_err_corrected_total"
	MLULinkCounterErrCRC24            = "mlulink_err_crc24_total"
	MLULinkCounterErrCRC32            = "mlulink_err_crc32_total"
	MLULinkCounterErrEccDouble        = "mlulink_err_ecc_double_total"
	MLULinkCounterErrFatal            = "mlulink_err_fatal_total"
	MLULinkCounterErrReplay           = "mlulink_err_replay_total"
	MLULinkCounterErrUncorrected      = "mlulink_err_uncorrected_total"
	MLULinkPortMode                   = "mlulink_port_mode"
	MLULinkSpeedFormat                = "mlulink_speed_format"
	MLULinkSpeedValue                 = "mlulink_speed"
	MLULinkStatusIsActive             = "mlulink_status"
	MLULinkStatusSerdesState          = "mlulink_serdes_status"
	MLULinkVersion                    = "mlulink_version"
	NUMANodeID                        = "numa_node_id"
	ParityError                       = "parity_error"
	PCIeInfo                          = "pcie_info"
	PCIeReadThroughput                = "pcie_read_throughput"
	PCIeReplayCount                   = "pcie_replay_count"
	PCIeWriteThroughput               = "pcie_write_throughput"
	PowerUsage                        = "power_usage"
	ProcessIpuUtil                    = "process_ipu_utilization"
	ProcessJpuUtil                    = "process_jpu_utilization"
	ProcessMemoryUtil                 = "process_memory_utilization"
	ProcessVpuDecodeUtil              = "process_vpu_decode_utilization"
	ProcessVpuEncodeUtil              = "process_vpu_encode_utilization"
	RemappedCorrectRows               = "remapped_correct_rows"
	RemappedFailedRows                = "remapped_failed_rows"
	RemappedPendingRows               = "remapped_pending_rows"
	RemappedUncorrectRows             = "remapped_uncorrect_rows"
	SingleBitRetiredPageCount         = "single_bit_retired_page_count"
	SramEccDbeCount                   = "sram_ecc_dbe_count"
	SramEccParityCount                = "sram_ecc_parity_count"
	SramEccSbeCount                   = "sram_ecc_sbe_count"
	Temperature                       = "temperature"
	TinyCoreUtil                      = "tiny_core_utilization"
	Util                              = "utilization"
	Version                           = "version"
	VideoCodecUtil                    = "video_codec_utilization"
	VirtualFunctionMemUtil            = "virtual_function_memory_utilization"
	VirtualFunctionPowerUsage         = "virtual_function_power_usage"
	VirtualFunctionUtil               = "virtual_function_utilization"
	VirtualMemTotal                   = "virtual_memory_total"
	VirtualMemUsed                    = "virtual_memory_used"
	XIDErrorCount                     = "xid_error_count"
	LastXIDError                      = "last_xid_error"
	XIDError                          = "xid_error"

	Allocated = "allocated"
	Container = "container"

	PCIeRead     = "pcie_read"
	PCIeWrite    = "pcie_write"
	DramRead     = "dram_read"
	DramWrite    = "dram_write"
	MLULinkRead  = "mlulink_read"
	MLULinkWrite = "mlulink_write"

	HostCPUTotal = "host_cpu_total"
	HostCPUIdle  = "host_cpu_idle"
	HostMemTotal = "host_memory_total"
	HostMemFree  = "host_memory_free"

	MLU                  = "mlu"
	Model                = "model"
	Type                 = "type"
	SN                   = "sn"
	UUID                 = "uuid"
	Node                 = "node"
	Cluster              = "cluster"
	Core                 = "core"
	CPUCore              = "cpu_core"
	MCU                  = "mcu"
	Driver               = "driver"
	Link                 = "link"
	LinkVersion          = "link_version"
	PCIeSlot             = "pcie_slot"
	PCIeSubsystem        = "pcie_subsystem"
	PCIeDeviceID         = "pcie_device_id"
	PCIeVendor           = "pcie_vendor"
	PCIeSubsystemVendor  = "pcie_subsystem_vendor"
	PCIeID               = "pcie_id"
	PCIeSpeed            = "pcie_speed"
	PCIeWidth            = "pcie_width"
	Pid                  = "pid"
	MemoryDie            = "memory_die"
	XID                  = "xid"
	XIDTimestamp         = "xid_timestamp"
	XIDComputeInstanceID = "xid_compute_instance_id"
	XIDMLUInstanceID     = "xid_mlu_instance_id"

	Namespace = "namespace"
	Pod       = "pod"
	VF        = "vf"
)
