// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Cambricon/mlu-exporter/pkg/cndev (interfaces: Cndev)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	cndev "github.com/Cambricon/mlu-exporter/pkg/cndev"
	gomock "github.com/golang/mock/gomock"
)

// Cndev is a mock of Cndev interface.
type Cndev struct {
	ctrl     *gomock.Controller
	recorder *CndevMockRecorder
}

// CndevMockRecorder is the mock recorder for Cndev.
type CndevMockRecorder struct {
	mock *Cndev
}

// NewCndev creates a new mock instance.
func NewCndev(ctrl *gomock.Controller) *Cndev {
	mock := &Cndev{ctrl: ctrl}
	mock.recorder = &CndevMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Cndev) EXPECT() *CndevMockRecorder {
	return m.recorder
}

// DeviceMimModeEnabled mocks base method.
func (m *Cndev) DeviceMimModeEnabled(arg0 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceMimModeEnabled", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceMimModeEnabled indicates an expected call of DeviceMimModeEnabled.
func (mr *CndevMockRecorder) DeviceMimModeEnabled(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceMimModeEnabled", reflect.TypeOf((*Cndev)(nil).DeviceMimModeEnabled), arg0)
}

// DeviceSmluModeEnabled mocks base method.
func (m *Cndev) DeviceSmluModeEnabled(arg0 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceSmluModeEnabled", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceSmluModeEnabled indicates an expected call of DeviceSmluModeEnabled.
func (mr *CndevMockRecorder) DeviceSmluModeEnabled(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceSmluModeEnabled", reflect.TypeOf((*Cndev)(nil).DeviceSmluModeEnabled), arg0)
}

// GetAllMLUInstanceInfo mocks base method.
func (m *Cndev) GetAllMLUInstanceInfo(arg0 uint) ([]cndev.MimInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMLUInstanceInfo", arg0)
	ret0, _ := ret[0].([]cndev.MimInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMLUInstanceInfo indicates an expected call of GetAllMLUInstanceInfo.
func (mr *CndevMockRecorder) GetAllMLUInstanceInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMLUInstanceInfo", reflect.TypeOf((*Cndev)(nil).GetAllMLUInstanceInfo), arg0)
}

// GetAllSMluInfo mocks base method.
func (m *Cndev) GetAllSMluInfo(arg0 uint) ([]cndev.SmluInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSMluInfo", arg0)
	ret0, _ := ret[0].([]cndev.SmluInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSMluInfo indicates an expected call of GetAllSMluInfo.
func (mr *CndevMockRecorder) GetAllSMluInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSMluInfo", reflect.TypeOf((*Cndev)(nil).GetAllSMluInfo), arg0)
}

// GetDeviceAddressSwaps mocks base method.
func (m *Cndev) GetDeviceAddressSwaps(arg0 uint) (uint32, uint32, uint32, uint32, uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceAddressSwaps", arg0)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(uint32)
	ret3, _ := ret[3].(uint32)
	ret4, _ := ret[4].(uint32)
	ret5, _ := ret[5].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5
}

// GetDeviceAddressSwaps indicates an expected call of GetDeviceAddressSwaps.
func (mr *CndevMockRecorder) GetDeviceAddressSwaps(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceAddressSwaps", reflect.TypeOf((*Cndev)(nil).GetDeviceAddressSwaps), arg0)
}

// GetDeviceArmOsMemory mocks base method.
func (m *Cndev) GetDeviceArmOsMemory(arg0 uint) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceArmOsMemory", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceArmOsMemory indicates an expected call of GetDeviceArmOsMemory.
func (mr *CndevMockRecorder) GetDeviceArmOsMemory(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceArmOsMemory", reflect.TypeOf((*Cndev)(nil).GetDeviceArmOsMemory), arg0)
}

// GetDeviceBAR4MemoryInfo mocks base method.
func (m *Cndev) GetDeviceBAR4MemoryInfo(arg0 uint) (uint64, uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceBAR4MemoryInfo", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDeviceBAR4MemoryInfo indicates an expected call of GetDeviceBAR4MemoryInfo.
func (mr *CndevMockRecorder) GetDeviceBAR4MemoryInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceBAR4MemoryInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceBAR4MemoryInfo), arg0)
}

// GetDeviceCPUUtil mocks base method.
func (m *Cndev) GetDeviceCPUUtil(arg0 uint) (uint16, []byte, []byte, []byte, []byte, []byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCPUUtil", arg0)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].([]byte)
	ret3, _ := ret[3].([]byte)
	ret4, _ := ret[4].([]byte)
	ret5, _ := ret[5].([]byte)
	ret6, _ := ret[6].([]byte)
	ret7, _ := ret[7].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5, ret6, ret7
}

// GetDeviceCPUUtil indicates an expected call of GetDeviceCPUUtil.
func (mr *CndevMockRecorder) GetDeviceCPUUtil(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCPUUtil", reflect.TypeOf((*Cndev)(nil).GetDeviceCPUUtil), arg0)
}

// GetDeviceCRCInfo mocks base method.
func (m *Cndev) GetDeviceCRCInfo(arg0 uint) (uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCRCInfo", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceCRCInfo indicates an expected call of GetDeviceCRCInfo.
func (mr *CndevMockRecorder) GetDeviceCRCInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCRCInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceCRCInfo), arg0)
}

// GetDeviceClusterCount mocks base method.
func (m *Cndev) GetDeviceClusterCount(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceClusterCount", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceClusterCount indicates an expected call of GetDeviceClusterCount.
func (mr *CndevMockRecorder) GetDeviceClusterCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceClusterCount", reflect.TypeOf((*Cndev)(nil).GetDeviceClusterCount), arg0)
}

// GetDeviceCndevVersion mocks base method.
func (m *Cndev) GetDeviceCndevVersion() (uint, uint, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCndevVersion")
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(uint)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDeviceCndevVersion indicates an expected call of GetDeviceCndevVersion.
func (mr *CndevMockRecorder) GetDeviceCndevVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCndevVersion", reflect.TypeOf((*Cndev)(nil).GetDeviceCndevVersion))
}

// GetDeviceComputeCapability mocks base method.
func (m *Cndev) GetDeviceComputeCapability(arg0 uint) (uint, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceComputeCapability", arg0)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceComputeCapability indicates an expected call of GetDeviceComputeCapability.
func (mr *CndevMockRecorder) GetDeviceComputeCapability(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceComputeCapability", reflect.TypeOf((*Cndev)(nil).GetDeviceComputeCapability), arg0)
}

// GetDeviceCoreNum mocks base method.
func (m *Cndev) GetDeviceCoreNum(arg0 uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCoreNum", arg0)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceCoreNum indicates an expected call of GetDeviceCoreNum.
func (mr *CndevMockRecorder) GetDeviceCoreNum(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCoreNum", reflect.TypeOf((*Cndev)(nil).GetDeviceCoreNum), arg0)
}

// GetDeviceCount mocks base method.
func (m *Cndev) GetDeviceCount() (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCount")
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceCount indicates an expected call of GetDeviceCount.
func (mr *CndevMockRecorder) GetDeviceCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCount", reflect.TypeOf((*Cndev)(nil).GetDeviceCount))
}

// GetDeviceCurrentInfo mocks base method.
func (m *Cndev) GetDeviceCurrentInfo(arg0 uint) (int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCurrentInfo", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDeviceCurrentInfo indicates an expected call of GetDeviceCurrentInfo.
func (mr *CndevMockRecorder) GetDeviceCurrentInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCurrentInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceCurrentInfo), arg0)
}

// GetDeviceCurrentPCIeInfo mocks base method.
func (m *Cndev) GetDeviceCurrentPCIeInfo(arg0 uint) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCurrentPCIeInfo", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceCurrentPCIeInfo indicates an expected call of GetDeviceCurrentPCIeInfo.
func (mr *CndevMockRecorder) GetDeviceCurrentPCIeInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCurrentPCIeInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceCurrentPCIeInfo), arg0)
}

// GetDeviceDDRInfo mocks base method.
func (m *Cndev) GetDeviceDDRInfo(arg0 uint) (int, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceDDRInfo", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceDDRInfo indicates an expected call of GetDeviceDDRInfo.
func (mr *CndevMockRecorder) GetDeviceDDRInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceDDRInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceDDRInfo), arg0)
}

// GetDeviceECCInfo mocks base method.
func (m *Cndev) GetDeviceECCInfo(arg0 uint) (uint64, uint64, uint64, uint64, uint64, uint64, uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceECCInfo", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(uint64)
	ret4, _ := ret[4].(uint64)
	ret5, _ := ret[5].(uint64)
	ret6, _ := ret[6].(uint64)
	ret7, _ := ret[7].(uint64)
	ret8, _ := ret[8].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5, ret6, ret7, ret8
}

// GetDeviceECCInfo indicates an expected call of GetDeviceECCInfo.
func (mr *CndevMockRecorder) GetDeviceECCInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceECCInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceECCInfo), arg0)
}

// GetDeviceEccMode mocks base method.
func (m *Cndev) GetDeviceEccMode(arg0 uint) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceEccMode", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceEccMode indicates an expected call of GetDeviceEccMode.
func (mr *CndevMockRecorder) GetDeviceEccMode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceEccMode", reflect.TypeOf((*Cndev)(nil).GetDeviceEccMode), arg0)
}

// GetDeviceFanSpeed mocks base method.
func (m *Cndev) GetDeviceFanSpeed(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceFanSpeed", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceFanSpeed indicates an expected call of GetDeviceFanSpeed.
func (mr *CndevMockRecorder) GetDeviceFanSpeed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceFanSpeed", reflect.TypeOf((*Cndev)(nil).GetDeviceFanSpeed), arg0)
}

// GetDeviceFrequency mocks base method.
func (m *Cndev) GetDeviceFrequency(arg0 uint) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceFrequency", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceFrequency indicates an expected call of GetDeviceFrequency.
func (mr *CndevMockRecorder) GetDeviceFrequency(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceFrequency", reflect.TypeOf((*Cndev)(nil).GetDeviceFrequency), arg0)
}

// GetDeviceHealth mocks base method.
func (m *Cndev) GetDeviceHealth(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceHealth", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceHealth indicates an expected call of GetDeviceHealth.
func (mr *CndevMockRecorder) GetDeviceHealth(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceHealth", reflect.TypeOf((*Cndev)(nil).GetDeviceHealth), arg0)
}

// GetDeviceHeartbeatCount mocks base method.
func (m *Cndev) GetDeviceHeartbeatCount(arg0 uint) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceHeartbeatCount", arg0)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceHeartbeatCount indicates an expected call of GetDeviceHeartbeatCount.
func (mr *CndevMockRecorder) GetDeviceHeartbeatCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceHeartbeatCount", reflect.TypeOf((*Cndev)(nil).GetDeviceHeartbeatCount), arg0)
}

// GetDeviceImageCodecUtil mocks base method.
func (m *Cndev) GetDeviceImageCodecUtil(arg0 uint) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceImageCodecUtil", arg0)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceImageCodecUtil indicates an expected call of GetDeviceImageCodecUtil.
func (mr *CndevMockRecorder) GetDeviceImageCodecUtil(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceImageCodecUtil", reflect.TypeOf((*Cndev)(nil).GetDeviceImageCodecUtil), arg0)
}

// GetDeviceMLUInstanceByID mocks base method.
func (m *Cndev) GetDeviceMLUInstanceByID(arg0 uint, arg1 int) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLUInstanceByID", arg0, arg1)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMLUInstanceByID indicates an expected call of GetDeviceMLUInstanceByID.
func (mr *CndevMockRecorder) GetDeviceMLUInstanceByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLUInstanceByID", reflect.TypeOf((*Cndev)(nil).GetDeviceMLUInstanceByID), arg0, arg1)
}

// GetDeviceMLULinkCapability mocks base method.
func (m *Cndev) GetDeviceMLULinkCapability(arg0, arg1 uint) (uint, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkCapability", arg0, arg1)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceMLULinkCapability indicates an expected call of GetDeviceMLULinkCapability.
func (mr *CndevMockRecorder) GetDeviceMLULinkCapability(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkCapability", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkCapability), arg0, arg1)
}

// GetDeviceMLULinkCounter mocks base method.
func (m *Cndev) GetDeviceMLULinkCounter(arg0, arg1 uint) (uint64, uint64, uint64, uint64, uint64, uint64, uint64, uint64, uint64, uint64, uint64, uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkCounter", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(uint64)
	ret4, _ := ret[4].(uint64)
	ret5, _ := ret[5].(uint64)
	ret6, _ := ret[6].(uint64)
	ret7, _ := ret[7].(uint64)
	ret8, _ := ret[8].(uint64)
	ret9, _ := ret[9].(uint64)
	ret10, _ := ret[10].(uint64)
	ret11, _ := ret[11].(uint64)
	ret12, _ := ret[12].(uint64)
	ret13, _ := ret[13].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5, ret6, ret7, ret8, ret9, ret10, ret11, ret12, ret13
}

// GetDeviceMLULinkCounter indicates an expected call of GetDeviceMLULinkCounter.
func (mr *CndevMockRecorder) GetDeviceMLULinkCounter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkCounter", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkCounter), arg0, arg1)
}

// GetDeviceMLULinkErrorCounter mocks base method.
func (m *Cndev) GetDeviceMLULinkErrorCounter(arg0, arg1 uint) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkErrorCounter", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMLULinkErrorCounter indicates an expected call of GetDeviceMLULinkErrorCounter.
func (mr *CndevMockRecorder) GetDeviceMLULinkErrorCounter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkErrorCounter", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkErrorCounter), arg0, arg1)
}

// GetDeviceMLULinkEventCounter mocks base method.
func (m *Cndev) GetDeviceMLULinkEventCounter(arg0, arg1 uint) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkEventCounter", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMLULinkEventCounter indicates an expected call of GetDeviceMLULinkEventCounter.
func (mr *CndevMockRecorder) GetDeviceMLULinkEventCounter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkEventCounter", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkEventCounter), arg0, arg1)
}

// GetDeviceMLULinkPortMode mocks base method.
func (m *Cndev) GetDeviceMLULinkPortMode(arg0, arg1 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkPortMode", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMLULinkPortMode indicates an expected call of GetDeviceMLULinkPortMode.
func (mr *CndevMockRecorder) GetDeviceMLULinkPortMode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkPortMode", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkPortMode), arg0, arg1)
}

// GetDeviceMLULinkPortNumber mocks base method.
func (m *Cndev) GetDeviceMLULinkPortNumber(arg0 uint) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkPortNumber", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetDeviceMLULinkPortNumber indicates an expected call of GetDeviceMLULinkPortNumber.
func (mr *CndevMockRecorder) GetDeviceMLULinkPortNumber(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkPortNumber", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkPortNumber), arg0)
}

// GetDeviceMLULinkRemoteInfo mocks base method.
func (m *Cndev) GetDeviceMLULinkRemoteInfo(arg0, arg1 uint) (uint64, uint64, uint32, uint32, int32, uint64, string, string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkRemoteInfo", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(uint32)
	ret3, _ := ret[3].(uint32)
	ret4, _ := ret[4].(int32)
	ret5, _ := ret[5].(uint64)
	ret6, _ := ret[6].(string)
	ret7, _ := ret[7].(string)
	ret8, _ := ret[8].(string)
	ret9, _ := ret[9].(string)
	ret10, _ := ret[10].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5, ret6, ret7, ret8, ret9, ret10
}

// GetDeviceMLULinkRemoteInfo indicates an expected call of GetDeviceMLULinkRemoteInfo.
func (mr *CndevMockRecorder) GetDeviceMLULinkRemoteInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkRemoteInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkRemoteInfo), arg0, arg1)
}

// GetDeviceMLULinkSpeedInfo mocks base method.
func (m *Cndev) GetDeviceMLULinkSpeedInfo(arg0, arg1 uint) (float32, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkSpeedInfo", arg0, arg1)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceMLULinkSpeedInfo indicates an expected call of GetDeviceMLULinkSpeedInfo.
func (mr *CndevMockRecorder) GetDeviceMLULinkSpeedInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkSpeedInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkSpeedInfo), arg0, arg1)
}

// GetDeviceMLULinkStatus mocks base method.
func (m *Cndev) GetDeviceMLULinkStatus(arg0, arg1 uint) (int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkStatus", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDeviceMLULinkStatus indicates an expected call of GetDeviceMLULinkStatus.
func (mr *CndevMockRecorder) GetDeviceMLULinkStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkStatus", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkStatus), arg0, arg1)
}

// GetDeviceMLULinkVersion mocks base method.
func (m *Cndev) GetDeviceMLULinkVersion(arg0, arg1 uint) (uint, uint, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMLULinkVersion", arg0, arg1)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(uint)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDeviceMLULinkVersion indicates an expected call of GetDeviceMLULinkVersion.
func (mr *CndevMockRecorder) GetDeviceMLULinkVersion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMLULinkVersion", reflect.TypeOf((*Cndev)(nil).GetDeviceMLULinkVersion), arg0, arg1)
}

// GetDeviceMaxPCIeInfo mocks base method.
func (m *Cndev) GetDeviceMaxPCIeInfo(arg0 uint) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMaxPCIeInfo", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceMaxPCIeInfo indicates an expected call of GetDeviceMaxPCIeInfo.
func (mr *CndevMockRecorder) GetDeviceMaxPCIeInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMaxPCIeInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceMaxPCIeInfo), arg0)
}

// GetDeviceMemEccCounter mocks base method.
func (m *Cndev) GetDeviceMemEccCounter(arg0 uint) ([]uint32, []uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMemEccCounter", arg0)
	ret0, _ := ret[0].([]uint32)
	ret1, _ := ret[1].([]uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceMemEccCounter indicates an expected call of GetDeviceMemEccCounter.
func (mr *CndevMockRecorder) GetDeviceMemEccCounter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMemEccCounter", reflect.TypeOf((*Cndev)(nil).GetDeviceMemEccCounter), arg0)
}

// GetDeviceMemory mocks base method.
func (m *Cndev) GetDeviceMemory(arg0 uint) (int64, int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMemory", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(int64)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetDeviceMemory indicates an expected call of GetDeviceMemory.
func (mr *CndevMockRecorder) GetDeviceMemory(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMemory", reflect.TypeOf((*Cndev)(nil).GetDeviceMemory), arg0)
}

// GetDeviceMemoryDieCount mocks base method.
func (m *Cndev) GetDeviceMemoryDieCount(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMemoryDieCount", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMemoryDieCount indicates an expected call of GetDeviceMemoryDieCount.
func (mr *CndevMockRecorder) GetDeviceMemoryDieCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMemoryDieCount", reflect.TypeOf((*Cndev)(nil).GetDeviceMemoryDieCount), arg0)
}

// GetDeviceMimProfileInfo mocks base method.
func (m *Cndev) GetDeviceMimProfileInfo(arg0 uint) ([]cndev.MimProfileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMimProfileInfo", arg0)
	ret0, _ := ret[0].([]cndev.MimProfileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMimProfileInfo indicates an expected call of GetDeviceMimProfileInfo.
func (mr *CndevMockRecorder) GetDeviceMimProfileInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMimProfileInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceMimProfileInfo), arg0)
}

// GetDeviceMimProfileMaxInstanceCount mocks base method.
func (m *Cndev) GetDeviceMimProfileMaxInstanceCount(arg0, arg1 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMimProfileMaxInstanceCount", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMimProfileMaxInstanceCount indicates an expected call of GetDeviceMimProfileMaxInstanceCount.
func (mr *CndevMockRecorder) GetDeviceMimProfileMaxInstanceCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMimProfileMaxInstanceCount", reflect.TypeOf((*Cndev)(nil).GetDeviceMimProfileMaxInstanceCount), arg0, arg1)
}

// GetDeviceModel mocks base method.
func (m *Cndev) GetDeviceModel(arg0 uint) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceModel", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDeviceModel indicates an expected call of GetDeviceModel.
func (mr *CndevMockRecorder) GetDeviceModel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceModel", reflect.TypeOf((*Cndev)(nil).GetDeviceModel), arg0)
}

// GetDeviceNUMANodeID mocks base method.
func (m *Cndev) GetDeviceNUMANodeID(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceNUMANodeID", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceNUMANodeID indicates an expected call of GetDeviceNUMANodeID.
func (mr *CndevMockRecorder) GetDeviceNUMANodeID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceNUMANodeID", reflect.TypeOf((*Cndev)(nil).GetDeviceNUMANodeID), arg0)
}

// GetDeviceOpticalInfo mocks base method.
func (m *Cndev) GetDeviceOpticalInfo(arg0, arg1 uint) (byte, float32, float32, []float32, []float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceOpticalInfo", arg0, arg1)
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(float32)
	ret2, _ := ret[2].(float32)
	ret3, _ := ret[3].([]float32)
	ret4, _ := ret[4].([]float32)
	ret5, _ := ret[5].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5
}

// GetDeviceOpticalInfo indicates an expected call of GetDeviceOpticalInfo.
func (mr *CndevMockRecorder) GetDeviceOpticalInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceOpticalInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceOpticalInfo), arg0, arg1)
}

// GetDeviceOverTemperatureInfo mocks base method.
func (m *Cndev) GetDeviceOverTemperatureInfo(arg0 uint) (uint32, uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceOverTemperatureInfo", arg0)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceOverTemperatureInfo indicates an expected call of GetDeviceOverTemperatureInfo.
func (mr *CndevMockRecorder) GetDeviceOverTemperatureInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceOverTemperatureInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceOverTemperatureInfo), arg0)
}

// GetDeviceOverTemperatureShutdownThreshold mocks base method.
func (m *Cndev) GetDeviceOverTemperatureShutdownThreshold(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceOverTemperatureShutdownThreshold", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceOverTemperatureShutdownThreshold indicates an expected call of GetDeviceOverTemperatureShutdownThreshold.
func (mr *CndevMockRecorder) GetDeviceOverTemperatureShutdownThreshold(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceOverTemperatureShutdownThreshold", reflect.TypeOf((*Cndev)(nil).GetDeviceOverTemperatureShutdownThreshold), arg0)
}

// GetDeviceOverTemperatureSlowdownThreshold mocks base method.
func (m *Cndev) GetDeviceOverTemperatureSlowdownThreshold(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceOverTemperatureSlowdownThreshold", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceOverTemperatureSlowdownThreshold indicates an expected call of GetDeviceOverTemperatureSlowdownThreshold.
func (mr *CndevMockRecorder) GetDeviceOverTemperatureSlowdownThreshold(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceOverTemperatureSlowdownThreshold", reflect.TypeOf((*Cndev)(nil).GetDeviceOverTemperatureSlowdownThreshold), arg0)
}

// GetDevicePCIeInfo mocks base method.
func (m *Cndev) GetDevicePCIeInfo(arg0 uint) (int, uint, uint, uint16, uint16, uint, uint, uint, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePCIeInfo", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(uint)
	ret3, _ := ret[3].(uint16)
	ret4, _ := ret[4].(uint16)
	ret5, _ := ret[5].(uint)
	ret6, _ := ret[6].(uint)
	ret7, _ := ret[7].(uint)
	ret8, _ := ret[8].(uint)
	ret9, _ := ret[9].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5, ret6, ret7, ret8, ret9
}

// GetDevicePCIeInfo indicates an expected call of GetDevicePCIeInfo.
func (mr *CndevMockRecorder) GetDevicePCIeInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePCIeInfo", reflect.TypeOf((*Cndev)(nil).GetDevicePCIeInfo), arg0)
}

// GetDevicePCIeReplayCount mocks base method.
func (m *Cndev) GetDevicePCIeReplayCount(arg0 uint) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePCIeReplayCount", arg0)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicePCIeReplayCount indicates an expected call of GetDevicePCIeReplayCount.
func (mr *CndevMockRecorder) GetDevicePCIeReplayCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePCIeReplayCount", reflect.TypeOf((*Cndev)(nil).GetDevicePCIeReplayCount), arg0)
}

// GetDevicePCIeThroughput mocks base method.
func (m *Cndev) GetDevicePCIeThroughput(arg0 uint) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePCIeThroughput", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDevicePCIeThroughput indicates an expected call of GetDevicePCIeThroughput.
func (mr *CndevMockRecorder) GetDevicePCIeThroughput(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePCIeThroughput", reflect.TypeOf((*Cndev)(nil).GetDevicePCIeThroughput), arg0)
}

// GetDeviceParityError mocks base method.
func (m *Cndev) GetDeviceParityError(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceParityError", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceParityError indicates an expected call of GetDeviceParityError.
func (mr *CndevMockRecorder) GetDeviceParityError(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceParityError", reflect.TypeOf((*Cndev)(nil).GetDeviceParityError), arg0)
}

// GetDevicePerformanceThrottleReason mocks base method.
func (m *Cndev) GetDevicePerformanceThrottleReason(arg0 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePerformanceThrottleReason", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicePerformanceThrottleReason indicates an expected call of GetDevicePerformanceThrottleReason.
func (mr *CndevMockRecorder) GetDevicePerformanceThrottleReason(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePerformanceThrottleReason", reflect.TypeOf((*Cndev)(nil).GetDevicePerformanceThrottleReason), arg0)
}

// GetDevicePower mocks base method.
func (m *Cndev) GetDevicePower(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePower", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicePower indicates an expected call of GetDevicePower.
func (mr *CndevMockRecorder) GetDevicePower(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePower", reflect.TypeOf((*Cndev)(nil).GetDevicePower), arg0)
}

// GetDevicePowerManagementDefaultLimitation mocks base method.
func (m *Cndev) GetDevicePowerManagementDefaultLimitation(arg0 uint) (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePowerManagementDefaultLimitation", arg0)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicePowerManagementDefaultLimitation indicates an expected call of GetDevicePowerManagementDefaultLimitation.
func (mr *CndevMockRecorder) GetDevicePowerManagementDefaultLimitation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePowerManagementDefaultLimitation", reflect.TypeOf((*Cndev)(nil).GetDevicePowerManagementDefaultLimitation), arg0)
}

// GetDevicePowerManagementLimitRange mocks base method.
func (m *Cndev) GetDevicePowerManagementLimitRange(arg0 uint) (uint16, uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePowerManagementLimitRange", arg0)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(uint16)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDevicePowerManagementLimitRange indicates an expected call of GetDevicePowerManagementLimitRange.
func (mr *CndevMockRecorder) GetDevicePowerManagementLimitRange(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePowerManagementLimitRange", reflect.TypeOf((*Cndev)(nil).GetDevicePowerManagementLimitRange), arg0)
}

// GetDevicePowerManagementLimitation mocks base method.
func (m *Cndev) GetDevicePowerManagementLimitation(arg0 uint) (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePowerManagementLimitation", arg0)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicePowerManagementLimitation indicates an expected call of GetDevicePowerManagementLimitation.
func (mr *CndevMockRecorder) GetDevicePowerManagementLimitation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePowerManagementLimitation", reflect.TypeOf((*Cndev)(nil).GetDevicePowerManagementLimitation), arg0)
}

// GetDeviceProcessUtil mocks base method.
func (m *Cndev) GetDeviceProcessUtil(arg0 uint) ([]uint32, []uint32, []uint32, []uint32, []uint32, []uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceProcessUtil", arg0)
	ret0, _ := ret[0].([]uint32)
	ret1, _ := ret[1].([]uint32)
	ret2, _ := ret[2].([]uint32)
	ret3, _ := ret[3].([]uint32)
	ret4, _ := ret[4].([]uint32)
	ret5, _ := ret[5].([]uint32)
	ret6, _ := ret[6].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5, ret6
}

// GetDeviceProcessUtil indicates an expected call of GetDeviceProcessUtil.
func (mr *CndevMockRecorder) GetDeviceProcessUtil(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceProcessUtil", reflect.TypeOf((*Cndev)(nil).GetDeviceProcessUtil), arg0)
}

// GetDeviceRemappedRows mocks base method.
func (m *Cndev) GetDeviceRemappedRows(arg0 uint) (uint32, uint32, uint32, uint32, uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceRemappedRows", arg0)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(uint32)
	ret3, _ := ret[3].(uint32)
	ret4, _ := ret[4].(uint32)
	ret5, _ := ret[5].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5
}

// GetDeviceRemappedRows indicates an expected call of GetDeviceRemappedRows.
func (mr *CndevMockRecorder) GetDeviceRemappedRows(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceRemappedRows", reflect.TypeOf((*Cndev)(nil).GetDeviceRemappedRows), arg0)
}

// GetDeviceRetiredPageInfo mocks base method.
func (m *Cndev) GetDeviceRetiredPageInfo(arg0 uint) (uint32, uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceRetiredPageInfo", arg0)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceRetiredPageInfo indicates an expected call of GetDeviceRetiredPageInfo.
func (mr *CndevMockRecorder) GetDeviceRetiredPageInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceRetiredPageInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceRetiredPageInfo), arg0)
}

// GetDeviceRetiredPagesOperation mocks base method.
func (m *Cndev) GetDeviceRetiredPagesOperation(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceRetiredPagesOperation", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceRetiredPagesOperation indicates an expected call of GetDeviceRetiredPagesOperation.
func (mr *CndevMockRecorder) GetDeviceRetiredPagesOperation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceRetiredPagesOperation", reflect.TypeOf((*Cndev)(nil).GetDeviceRetiredPagesOperation), arg0)
}

// GetDeviceSMluProfileIDInfo mocks base method.
func (m *Cndev) GetDeviceSMluProfileIDInfo(arg0 uint) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceSMluProfileIDInfo", arg0)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceSMluProfileIDInfo indicates an expected call of GetDeviceSMluProfileIDInfo.
func (mr *CndevMockRecorder) GetDeviceSMluProfileIDInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceSMluProfileIDInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceSMluProfileIDInfo), arg0)
}

// GetDeviceSMluProfileInfo mocks base method.
func (m *Cndev) GetDeviceSMluProfileInfo(arg0, arg1 uint) (cndev.SmluProfileInfo, uint32, uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceSMluProfileInfo", arg0, arg1)
	ret0, _ := ret[0].(cndev.SmluProfileInfo)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(uint32)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDeviceSMluProfileInfo indicates an expected call of GetDeviceSMluProfileInfo.
func (mr *CndevMockRecorder) GetDeviceSMluProfileInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceSMluProfileInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceSMluProfileInfo), arg0, arg1)
}

// GetDeviceSN mocks base method.
func (m *Cndev) GetDeviceSN(arg0 uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceSN", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceSN indicates an expected call of GetDeviceSN.
func (mr *CndevMockRecorder) GetDeviceSN(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceSN", reflect.TypeOf((*Cndev)(nil).GetDeviceSN), arg0)
}

// GetDeviceTemperature mocks base method.
func (m *Cndev) GetDeviceTemperature(arg0 uint) (int, int, int, []int, []int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceTemperature", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].([]int)
	ret4, _ := ret[4].([]int)
	ret5, _ := ret[5].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5
}

// GetDeviceTemperature indicates an expected call of GetDeviceTemperature.
func (mr *CndevMockRecorder) GetDeviceTemperature(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceTemperature", reflect.TypeOf((*Cndev)(nil).GetDeviceTemperature), arg0)
}

// GetDeviceTinyCoreUtil mocks base method.
func (m *Cndev) GetDeviceTinyCoreUtil(arg0 uint) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceTinyCoreUtil", arg0)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceTinyCoreUtil indicates an expected call of GetDeviceTinyCoreUtil.
func (mr *CndevMockRecorder) GetDeviceTinyCoreUtil(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceTinyCoreUtil", reflect.TypeOf((*Cndev)(nil).GetDeviceTinyCoreUtil), arg0)
}

// GetDeviceUUID mocks base method.
func (m *Cndev) GetDeviceUUID(arg0 uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceUUID", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceUUID indicates an expected call of GetDeviceUUID.
func (mr *CndevMockRecorder) GetDeviceUUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceUUID", reflect.TypeOf((*Cndev)(nil).GetDeviceUUID), arg0)
}

// GetDeviceUtil mocks base method.
func (m *Cndev) GetDeviceUtil(arg0 uint) (int, []int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceUtil", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceUtil indicates an expected call of GetDeviceUtil.
func (mr *CndevMockRecorder) GetDeviceUtil(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceUtil", reflect.TypeOf((*Cndev)(nil).GetDeviceUtil), arg0)
}

// GetDeviceVersion mocks base method.
func (m *Cndev) GetDeviceVersion(arg0 uint) (uint, uint, uint, uint, uint, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceVersion", arg0)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(uint)
	ret3, _ := ret[3].(uint)
	ret4, _ := ret[4].(uint)
	ret5, _ := ret[5].(uint)
	ret6, _ := ret[6].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5, ret6
}

// GetDeviceVersion indicates an expected call of GetDeviceVersion.
func (mr *CndevMockRecorder) GetDeviceVersion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceVersion", reflect.TypeOf((*Cndev)(nil).GetDeviceVersion), arg0)
}

// GetDeviceVfState mocks base method.
func (m *Cndev) GetDeviceVfState(arg0 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceVfState", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceVfState indicates an expected call of GetDeviceVfState.
func (mr *CndevMockRecorder) GetDeviceVfState(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceVfState", reflect.TypeOf((*Cndev)(nil).GetDeviceVfState), arg0)
}

// GetDeviceVideoCodecUtil mocks base method.
func (m *Cndev) GetDeviceVideoCodecUtil(arg0 uint) ([]int, []int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceVideoCodecUtil", arg0)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].([]int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeviceVideoCodecUtil indicates an expected call of GetDeviceVideoCodecUtil.
func (mr *CndevMockRecorder) GetDeviceVideoCodecUtil(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceVideoCodecUtil", reflect.TypeOf((*Cndev)(nil).GetDeviceVideoCodecUtil), arg0)
}

// GetDeviceVoltageInfo mocks base method.
func (m *Cndev) GetDeviceVoltageInfo(arg0 uint) (int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceVoltageInfo", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDeviceVoltageInfo indicates an expected call of GetDeviceVoltageInfo.
func (mr *CndevMockRecorder) GetDeviceVoltageInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceVoltageInfo", reflect.TypeOf((*Cndev)(nil).GetDeviceVoltageInfo), arg0)
}

// GetSupportedEventTypes mocks base method.
func (m *Cndev) GetSupportedEventTypes(arg0 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedEventTypes", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetSupportedEventTypes indicates an expected call of GetSupportedEventTypes.
func (mr *CndevMockRecorder) GetSupportedEventTypes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedEventTypes", reflect.TypeOf((*Cndev)(nil).GetSupportedEventTypes), arg0)
}

// Init mocks base method.
func (m *Cndev) Init(arg0 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *CndevMockRecorder) Init(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*Cndev)(nil).Init), arg0)
}

// RegisterEventsHandleAndWait mocks base method.
func (m *Cndev) RegisterEventsHandleAndWait(arg0 []int, arg1 chan cndev.XIDInfoWithTimestamp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterEventsHandleAndWait", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterEventsHandleAndWait indicates an expected call of RegisterEventsHandleAndWait.
func (mr *CndevMockRecorder) RegisterEventsHandleAndWait(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEventsHandleAndWait", reflect.TypeOf((*Cndev)(nil).RegisterEventsHandleAndWait), arg0, arg1)
}

// Release mocks base method.
func (m *Cndev) Release() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release")
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *CndevMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*Cndev)(nil).Release))
}
