# Copyright 2020 Cambricon, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
data:
  metrics.yaml: |
    cndev:
      temperature:
        name: "temperature"
        help: "The temperature of Cambricon MLU, unit is 'celsius'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          cluster: "cluster"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      health:
        name: "health"
        help: "The health state of Cambricon MLU, 1 means health, 0 means sick"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      memory_total:
        name: "memory_total"
        help: "The total physical memory of Cambricon MLU, unit is 'B'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      memory_used:
        name: "memory_used"
        help: "The used physical memory of Cambricon MLU, unit is 'B'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      memory_utilization:
        name: "memory_utilization"
        help: "The memory utilization of Cambricon MLU, unit is '%'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      utilization:
        name: "utilization"
        help: "The utilization of Cambricon MLU, unit is '%'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      capacity:
        name: "capacity"
        help: "The capacity metric of Cambricon MLU, unit is 'T'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      usage:
        name: "usage"
        help: "The usage metric of Cambricon MLU, unit is 'T'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      core_utilization:
        name: "core"
        help: "The utilization metric of Cambricon MLU core, unit is '%'"
        labels:
          core: "core"
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      fan_speed:
        name: "fan_speed"
        help: "Fan speed of Cambricon MLU, unit is 'rpm', '-1' means no fan on MLU"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      power_usage:
        name: "power_usage"
        help: "The power usage of Cambricon MLU, unit is 'w'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      version:
        name: "version"
        help: "The version info of Cambricon MLU"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      virtual_memory_utilization:
        name: "virtual_memory_utilization"
        help: "The memory utilization of Cambricon MLU VF, unit is '%'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
          vf: "vf"
      virtual_function_utilization:
        name: "virtual_function_utilization"
        help: "The utilization of Cambricon MLU VF, unit is '%'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
          vf: "vf"
    podresources:
      allocated:
        name: "allocated"
        help: "The allocated number of Cambricon MLUs in a node"
        labels:
          model: "model"
          type: "type"
          driver: "driver"
          node: "node"
      container:
        name: "container"
        help: "The k8s container info of Cambricon MLUs allocated"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
          namespace: "namespace"
          pod: "pod"
          container: "container"
          vf: "vf"
    cnpapi:
      pcie_read:
        name: "pcie_read"
        help: "The pcie read io metric of Cambircon MLU, unit is 'GB'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      pcie_write:
        name: "pcie_write"
        help: "The pcie write io metric of Cambircon MLU, unit is 'GB'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      dram_read:
        name: "dram_read"
        help: "The dram read io metric of Cambircon MLU, unit is 'GB'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      dram_write:
        name: "dram_write"
        help: "The dram write io metric of Cambircon MLU, unit is 'GB'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      mlulink_read:
        name: "mlulink_read"
        help: "The mlulink read io metric of Cambircon MLU, unit is 'GB'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
      mlulink_write:
        name: "mlulink_write"
        help: "The mlulink write io metric of Cambircon MLU, unit is 'GB'"
        labels:
          mlu: "mlu"
          model: "model"
          type: "type"
          sn: "sn"
          uuid: "uuid"
          node: "node"
          mcu: "mcu"
          driver: "driver"
    host:
      host_cpu_total:
        name: "host_cpu_total"
        help: "The cpu total metric of host machine, unit is the same as which in /proc/stat"
        labels:
          node: "node"
      host_cpu_idle:
        name: "host_cpu_idle"
        help: "The cpu idle metric of host machine, unit is the same as which in /proc/stat"
        labels:
          node: "node"
      host_memory_total:
        name: "host_memory_total"
        help: "The memory total metric of host machine, unit is 'GB'"
        labels:
          node: "node"
      host_memory_free:
        name: "host_memory_free"
        help: "The memory idle metric of host machine, unit is 'GB'"
        labels:
          node: "node"
kind: ConfigMap
metadata:
  labels:
    app: mlu-monitoring
  name: cambricon-mlu-exporter
  namespace: kube-system
