---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mlu-exporter.name" . }}
  labels:
    {{- include "mlu-exporter.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mlu-exporter.name" . }}
    namespace: {{ include "mlu-exporter.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "mlu-exporter.name" . }}
  apiGroup: rbac.authorization.k8s.io
