---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlu-exporter.name" . }}
  namespace: {{ include "mlu-exporter.namespace" . }}
  labels:
    {{- include "mlu-exporter.labels" . | nindent 4 }}
