apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "mlu-exporter.labels" . | nindent 4 }}
  name: {{ include "mlu-exporter.fullname" . }}
  namespace: {{ include "mlu-exporter.namespace" . }}
spec:
  clusterIP: None
  ports:
  - port: 30108
    protocol: TCP
    name: http-metrics
    targetPort: 30108
  selector:
    {{- include "mlu-exporter.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
